spring.application.name=iot-web-app
# 1. Đổi cổng để chạy song song với ThingsBoard (8080)
server.port=8080

# 2. Kết nối đến MySQL (Dùng localhost:3307 vì bạn đang chạy app bằng lệnh ./mvnw)
spring.datasource.url=jdbc:mysql://localhost:3307/web_iot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=duc_user
spring.datasource.password=duc_password_123

# 3. Hibernate cấu hình
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Vô hiệu hóa tự động chạy SQL init vì đã khởi tạo thủ công
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Tắt cache Thymeleaf để phản ánh thay đổi ngay lập tức
spring.thymeleaf.cache=false