# 1. Port
server.port=8080

# 2. Ket noi MySQL (Railway inject qua bien moi truong SPRING_DATASOURCE_*)
# Cac gia tri nay se duoc ghi de boi bien moi truong cua Railway
spring.datasource.url=jdbc:mysql://db-web-iot:3306/iot_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=duc_user
spring.datasource.password=duc_password_123

# 3. Hibernate cau hinh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4. Vo hieu hoa tu dong chay SQL init
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Tat cache Thymeleaf de phan anh thay doi ngay lap tuc
spring.thymeleaf.cache=false

# 5. Cau hinh MQTT Broker
mqtt.broker.url=tcp://mosquitto-iot-web:1883
mqtt.topic.sensor=iot/sensor/data/+
