

services:
  # Service 1: Cơ sở dữ liệu MySQL
  db-web-iot:
    image: mysql:8.0
    container_name: mysql-iot-web
    restart: always
    environment:
      MYSQL_DATABASE: iot_db
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_USER: duc_user
      MYSQL_PASSWORD: duc_password_123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"  # Port 3307 để không trùng với MySQL/Postgres của ThingsBoard
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Service 2: Ứng dụng Java (Tạm thời để trống để build sau)
  java-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: iot-java-service
    ports:
      - "8081:8080"
    depends_on:
      - db-web-iot
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-web-iot:3306/iot_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=duc_user
      - SPRING_DATASOURCE_PASSWORD=duc_password_123
      - MQTT_BROKER_URL=ssl://10cf23427b77452faec8dc86e09f1bc1.s1.eu.hivemq.cloud:8883
      - MQTT_USERNAME=tienduc
      - MQTT_PASSWORD=D@ucffgh123

  # Service 3: MQTT Broker (Mosquitto)
  mosquitto-iot-web:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-iot-web
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
